version: '3'
services:
 db:
  container_name: game_db
  image: postgres:15.4-bullseye
  environment:
    POSTGRES_USER: gguser
    POSTGRES_PASSWORD: gguser
    PGDATA: /data/postgres
    POSTGRES_DB: gg_base
  volumes:
     - ./data:/data/postgres
  ports:
    - "5436:5432"
    