version: '3'
services:
  db:
    container_name: game_db
    image: postgres:15.4-bullseye
    environment:
      POSTGRES_USER: gguser
      POSTGRES_PASSWORD: gguser
      PGDATA: /data/postgres
      POSTGRES_DB: gg_base
    volumes:
      - ./data:/data/postgres
    ports:
      - "5436:5432"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "user-registration-topic:1:1,user-unsubscribe-topic:1:1"
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
